version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  grpc_service:
    container_name: grpc_server
    build:
      context: .
      dockerfile: Dockerfile_server
    network_mode: "host"
    depends_on:
      - db

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: telegram_bot
    network_mode: "host"
    depends_on:
      - db
      - grpc_service