apiVersion: v1
kind: Namespace
metadata:
  name: infamax
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
  namespace: infamax
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      namespace: mpak
      labels:
        app: grpc
    spec:
      containers:
        - name: grpc
          image: cr.yandex/crpa8gap9g6vl6hshofn/grpc-server:__VERSION__
          imagePullPolicy: Always
